# Generated by Django 3.2 on 2023-04-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=500)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('Filepath', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'data_tables',
            },
        ),
    ]
