# Generated by Django 3.2 on 2023-04-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgreeYaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_data',
            name='Phone',
            field=models.CharField(max_length=200),
        ),
    ]
