# Generated by Django 3.2 on 2023-04-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgreeYaApp', '0003_alter_record_data_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record_data',
            table=None,
        ),
    ]
