# Generated by Django 3.2 on 2023-04-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgreeYaApp', '0004_alter_record_data_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record_data',
            table='data_tables',
        ),
    ]
