# Generated by Django 3.2 on 2023-04-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgreeYaApp', '0005_alter_record_data_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_data',
            name='Phone',
            field=models.IntegerField(max_length=200),
        ),
    ]
